# Generated by Django 5.2.17 on 2026-10-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('pharmacy_owner', 'Pharmacy owner'), ('doctor', 'Doctor'), ('employee', 'Employee'), ('admin', 'Admin')], default='customer', max_length=30),
        ),
    ]
